// Generated by the protocol buffer compiler.  DO NOT EDIT!

@class PBDescriptorProto;
@class PBDescriptorProto_Builder;
@class PBDescriptorProto_ExtensionRange;
@class PBDescriptorProto_ExtensionRange_Builder;
@class PBEnumDescriptorProto;
@class PBEnumDescriptorProto_Builder;
@class PBEnumOptions;
@class PBEnumOptions_Builder;
@class PBEnumValueDescriptorProto;
@class PBEnumValueDescriptorProto_Builder;
@class PBEnumValueOptions;
@class PBEnumValueOptions_Builder;
@class PBFieldDescriptorProto;
@class PBFieldDescriptorProto_Builder;
@class PBFieldOptions;
@class PBFieldOptions_Builder;
@class PBFileDescriptorProto;
@class PBFileDescriptorProto_Builder;
@class PBFileDescriptorSet;
@class PBFileDescriptorSet_Builder;
@class PBFileOptions;
@class PBFileOptions_Builder;
@class PBMessageOptions;
@class PBMessageOptions_Builder;
@class PBMethodDescriptorProto;
@class PBMethodDescriptorProto_Builder;
@class PBMethodOptions;
@class PBMethodOptions_Builder;
@class PBServiceDescriptorProto;
@class PBServiceDescriptorProto_Builder;
@class PBServiceOptions;
@class PBServiceOptions_Builder;
@class PBUninterpretedOption;
@class PBUninterpretedOption_Builder;
@class PBUninterpretedOption_NamePart;
@class PBUninterpretedOption_NamePart_Builder;
typedef enum {
  PBFieldDescriptorProto_TypeTypeDouble = 1,
  PBFieldDescriptorProto_TypeTypeFloat = 2,
  PBFieldDescriptorProto_TypeTypeInt64 = 3,
  PBFieldDescriptorProto_TypeTypeUint64 = 4,
  PBFieldDescriptorProto_TypeTypeInt32 = 5,
  PBFieldDescriptorProto_TypeTypeFixed64 = 6,
  PBFieldDescriptorProto_TypeTypeFixed32 = 7,
  PBFieldDescriptorProto_TypeTypeBool = 8,
  PBFieldDescriptorProto_TypeTypeString = 9,
  PBFieldDescriptorProto_TypeTypeGroup = 10,
  PBFieldDescriptorProto_TypeTypeMessage = 11,
  PBFieldDescriptorProto_TypeTypeBytes = 12,
  PBFieldDescriptorProto_TypeTypeUint32 = 13,
  PBFieldDescriptorProto_TypeTypeEnum = 14,
  PBFieldDescriptorProto_TypeTypeSfixed32 = 15,
  PBFieldDescriptorProto_TypeTypeSfixed64 = 16,
  PBFieldDescriptorProto_TypeTypeSint32 = 17,
  PBFieldDescriptorProto_TypeTypeSint64 = 18,
} PBFieldDescriptorProto_Type;

BOOL PBFieldDescriptorProto_TypeIsValidValue(PBFieldDescriptorProto_Type value);

typedef enum {
  PBFieldDescriptorProto_LabelLabelOptional = 1,
  PBFieldDescriptorProto_LabelLabelRequired = 2,
  PBFieldDescriptorProto_LabelLabelRepeated = 3,
} PBFieldDescriptorProto_Label;

BOOL PBFieldDescriptorProto_LabelIsValidValue(PBFieldDescriptorProto_Label value);

typedef enum {
  PBFileOptions_OptimizeModeSpeed = 1,
  PBFileOptions_OptimizeModeCodeSize = 2,
  PBFileOptions_OptimizeModeLiteRuntime = 3,
} PBFileOptions_OptimizeMode;

BOOL PBFileOptions_OptimizeModeIsValidValue(PBFileOptions_OptimizeMode value);

typedef enum {
  PBFieldOptions_CTypeString = 0,
  PBFieldOptions_CTypeCord = 1,
  PBFieldOptions_CTypeStringPiece = 2,
} PBFieldOptions_CType;

BOOL PBFieldOptions_CTypeIsValidValue(PBFieldOptions_CType value);


@interface PBDescriptorRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface PBFileDescriptorSet : PBGeneratedMessage {
@private
  PBAppendableArray * fileArray;
}
@property (readonly, retain) PBArray * file;
- (PBFileDescriptorProto*)fileAtIndex:(NSUInteger)index;

+ (PBFileDescriptorSet*) defaultInstance;
- (PBFileDescriptorSet*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBFileDescriptorSet_Builder*) builder;
+ (PBFileDescriptorSet_Builder*) builder;
+ (PBFileDescriptorSet_Builder*) builderWithPrototype:(PBFileDescriptorSet*) prototype;

+ (PBFileDescriptorSet*) parseFromData:(NSData*) data;
+ (PBFileDescriptorSet*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFileDescriptorSet*) parseFromInputStream:(NSInputStream*) input;
+ (PBFileDescriptorSet*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFileDescriptorSet*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBFileDescriptorSet*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBFileDescriptorSet_Builder : PBGeneratedMessage_Builder {
@private
  PBFileDescriptorSet* result;
}

- (PBFileDescriptorSet*) defaultInstance;

- (PBFileDescriptorSet_Builder*) clear;
- (PBFileDescriptorSet_Builder*) clone;

- (PBFileDescriptorSet*) build;
- (PBFileDescriptorSet*) buildPartial;

- (PBFileDescriptorSet_Builder*) mergeFrom:(PBFileDescriptorSet*) other;
- (PBFileDescriptorSet_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBFileDescriptorSet_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (PBAppendableArray *)file;
- (PBFileDescriptorProto*)fileAtIndex:(NSUInteger)index;
- (PBFileDescriptorSet_Builder *)addFile:(PBFileDescriptorProto*)value;
- (PBFileDescriptorSet_Builder *)setFileArray:(NSArray *)array;
- (PBFileDescriptorSet_Builder *)setFileValues:(const PBFileDescriptorProto* *)values count:(NSUInteger)count;
- (PBFileDescriptorSet_Builder *)clearFile;
@end

@interface PBFileDescriptorProto : PBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasPackage_:1;
  BOOL hasOptions_:1;
  NSString* name;
  NSString* package;
  PBFileOptions* options;
  PBAppendableArray * dependencyArray;
  PBAppendableArray * messageTypeArray;
  PBAppendableArray * enumTypeArray;
  PBAppendableArray * serviceArray;
  PBAppendableArray * extensionArray;
}
- (BOOL) hasName;
- (BOOL) hasPackage;
- (BOOL) hasOptions;
@property (readonly, retain) NSString* name;
@property (readonly, retain) NSString* package;
@property (readonly, retain) PBArray * dependency;
@property (readonly, retain) PBArray * messageType;
@property (readonly, retain) PBArray * enumType;
@property (readonly, retain) PBArray * service;
@property (readonly, retain) PBArray * extension;
@property (readonly, retain) PBFileOptions* options;
- (NSString*)dependencyAtIndex:(NSUInteger)index;
- (PBDescriptorProto*)messageTypeAtIndex:(NSUInteger)index;
- (PBEnumDescriptorProto*)enumTypeAtIndex:(NSUInteger)index;
- (PBServiceDescriptorProto*)serviceAtIndex:(NSUInteger)index;
- (PBFieldDescriptorProto*)extensionAtIndex:(NSUInteger)index;

+ (PBFileDescriptorProto*) defaultInstance;
- (PBFileDescriptorProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBFileDescriptorProto_Builder*) builder;
+ (PBFileDescriptorProto_Builder*) builder;
+ (PBFileDescriptorProto_Builder*) builderWithPrototype:(PBFileDescriptorProto*) prototype;

+ (PBFileDescriptorProto*) parseFromData:(NSData*) data;
+ (PBFileDescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFileDescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (PBFileDescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFileDescriptorProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBFileDescriptorProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBFileDescriptorProto_Builder : PBGeneratedMessage_Builder {
@private
  PBFileDescriptorProto* result;
}

- (PBFileDescriptorProto*) defaultInstance;

- (PBFileDescriptorProto_Builder*) clear;
- (PBFileDescriptorProto_Builder*) clone;

- (PBFileDescriptorProto*) build;
- (PBFileDescriptorProto*) buildPartial;

- (PBFileDescriptorProto_Builder*) mergeFrom:(PBFileDescriptorProto*) other;
- (PBFileDescriptorProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBFileDescriptorProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (PBFileDescriptorProto_Builder*) setName:(NSString*) value;
- (PBFileDescriptorProto_Builder*) clearName;

- (BOOL) hasPackage;
- (NSString*) package;
- (PBFileDescriptorProto_Builder*) setPackage:(NSString*) value;
- (PBFileDescriptorProto_Builder*) clearPackage;

- (PBAppendableArray *)dependency;
- (NSString*)dependencyAtIndex:(NSUInteger)index;
- (PBFileDescriptorProto_Builder *)addDependency:(NSString*)value;
- (PBFileDescriptorProto_Builder *)setDependencyArray:(NSArray *)array;
- (PBFileDescriptorProto_Builder *)setDependencyValues:(const NSString* *)values count:(NSUInteger)count;
- (PBFileDescriptorProto_Builder *)clearDependency;

- (PBAppendableArray *)messageType;
- (PBDescriptorProto*)messageTypeAtIndex:(NSUInteger)index;
- (PBFileDescriptorProto_Builder *)addMessageType:(PBDescriptorProto*)value;
- (PBFileDescriptorProto_Builder *)setMessageTypeArray:(NSArray *)array;
- (PBFileDescriptorProto_Builder *)setMessageTypeValues:(const PBDescriptorProto* *)values count:(NSUInteger)count;
- (PBFileDescriptorProto_Builder *)clearMessageType;

- (PBAppendableArray *)enumType;
- (PBEnumDescriptorProto*)enumTypeAtIndex:(NSUInteger)index;
- (PBFileDescriptorProto_Builder *)addEnumType:(PBEnumDescriptorProto*)value;
- (PBFileDescriptorProto_Builder *)setEnumTypeArray:(NSArray *)array;
- (PBFileDescriptorProto_Builder *)setEnumTypeValues:(const PBEnumDescriptorProto* *)values count:(NSUInteger)count;
- (PBFileDescriptorProto_Builder *)clearEnumType;

- (PBAppendableArray *)service;
- (PBServiceDescriptorProto*)serviceAtIndex:(NSUInteger)index;
- (PBFileDescriptorProto_Builder *)addService:(PBServiceDescriptorProto*)value;
- (PBFileDescriptorProto_Builder *)setServiceArray:(NSArray *)array;
- (PBFileDescriptorProto_Builder *)setServiceValues:(const PBServiceDescriptorProto* *)values count:(NSUInteger)count;
- (PBFileDescriptorProto_Builder *)clearService;

- (PBAppendableArray *)extension;
- (PBFieldDescriptorProto*)extensionAtIndex:(NSUInteger)index;
- (PBFileDescriptorProto_Builder *)addExtension:(PBFieldDescriptorProto*)value;
- (PBFileDescriptorProto_Builder *)setExtensionArray:(NSArray *)array;
- (PBFileDescriptorProto_Builder *)setExtensionValues:(const PBFieldDescriptorProto* *)values count:(NSUInteger)count;
- (PBFileDescriptorProto_Builder *)clearExtension;

- (BOOL) hasOptions;
- (PBFileOptions*) options;
- (PBFileDescriptorProto_Builder*) setOptions:(PBFileOptions*) value;
- (PBFileDescriptorProto_Builder*) setOptionsBuilder:(PBFileOptions_Builder*) builderForValue;
- (PBFileDescriptorProto_Builder*) mergeOptions:(PBFileOptions*) value;
- (PBFileDescriptorProto_Builder*) clearOptions;
@end

@interface PBDescriptorProto : PBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasOptions_:1;
  NSString* name;
  PBMessageOptions* options;
  PBAppendableArray * fieldArray;
  PBAppendableArray * extensionArray;
  PBAppendableArray * nestedTypeArray;
  PBAppendableArray * enumTypeArray;
  PBAppendableArray * extensionRangeArray;
}
- (BOOL) hasName;
- (BOOL) hasOptions;
@property (readonly, retain) NSString* name;
@property (readonly, retain) PBArray * field;
@property (readonly, retain) PBArray * extension;
@property (readonly, retain) PBArray * nestedType;
@property (readonly, retain) PBArray * enumType;
@property (readonly, retain) PBArray * extensionRange;
@property (readonly, retain) PBMessageOptions* options;
- (PBFieldDescriptorProto*)fieldAtIndex:(NSUInteger)index;
- (PBFieldDescriptorProto*)extensionAtIndex:(NSUInteger)index;
- (PBDescriptorProto*)nestedTypeAtIndex:(NSUInteger)index;
- (PBEnumDescriptorProto*)enumTypeAtIndex:(NSUInteger)index;
- (PBDescriptorProto_ExtensionRange*)extensionRangeAtIndex:(NSUInteger)index;

+ (PBDescriptorProto*) defaultInstance;
- (PBDescriptorProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBDescriptorProto_Builder*) builder;
+ (PBDescriptorProto_Builder*) builder;
+ (PBDescriptorProto_Builder*) builderWithPrototype:(PBDescriptorProto*) prototype;

+ (PBDescriptorProto*) parseFromData:(NSData*) data;
+ (PBDescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBDescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (PBDescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBDescriptorProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBDescriptorProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBDescriptorProto_ExtensionRange : PBGeneratedMessage {
@private
  BOOL hasStart_:1;
  BOOL hasEnd_:1;
  int32_t start;
  int32_t end;
}
- (BOOL) hasStart;
- (BOOL) hasEnd;
@property (readonly) int32_t start;
@property (readonly) int32_t end;

+ (PBDescriptorProto_ExtensionRange*) defaultInstance;
- (PBDescriptorProto_ExtensionRange*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBDescriptorProto_ExtensionRange_Builder*) builder;
+ (PBDescriptorProto_ExtensionRange_Builder*) builder;
+ (PBDescriptorProto_ExtensionRange_Builder*) builderWithPrototype:(PBDescriptorProto_ExtensionRange*) prototype;

+ (PBDescriptorProto_ExtensionRange*) parseFromData:(NSData*) data;
+ (PBDescriptorProto_ExtensionRange*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBDescriptorProto_ExtensionRange*) parseFromInputStream:(NSInputStream*) input;
+ (PBDescriptorProto_ExtensionRange*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBDescriptorProto_ExtensionRange*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBDescriptorProto_ExtensionRange*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBDescriptorProto_ExtensionRange_Builder : PBGeneratedMessage_Builder {
@private
  PBDescriptorProto_ExtensionRange* result;
}

- (PBDescriptorProto_ExtensionRange*) defaultInstance;

- (PBDescriptorProto_ExtensionRange_Builder*) clear;
- (PBDescriptorProto_ExtensionRange_Builder*) clone;

- (PBDescriptorProto_ExtensionRange*) build;
- (PBDescriptorProto_ExtensionRange*) buildPartial;

- (PBDescriptorProto_ExtensionRange_Builder*) mergeFrom:(PBDescriptorProto_ExtensionRange*) other;
- (PBDescriptorProto_ExtensionRange_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBDescriptorProto_ExtensionRange_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStart;
- (int32_t) start;
- (PBDescriptorProto_ExtensionRange_Builder*) setStart:(int32_t) value;
- (PBDescriptorProto_ExtensionRange_Builder*) clearStart;

- (BOOL) hasEnd;
- (int32_t) end;
- (PBDescriptorProto_ExtensionRange_Builder*) setEnd:(int32_t) value;
- (PBDescriptorProto_ExtensionRange_Builder*) clearEnd;
@end

@interface PBDescriptorProto_Builder : PBGeneratedMessage_Builder {
@private
  PBDescriptorProto* result;
}

- (PBDescriptorProto*) defaultInstance;

- (PBDescriptorProto_Builder*) clear;
- (PBDescriptorProto_Builder*) clone;

- (PBDescriptorProto*) build;
- (PBDescriptorProto*) buildPartial;

- (PBDescriptorProto_Builder*) mergeFrom:(PBDescriptorProto*) other;
- (PBDescriptorProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBDescriptorProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (PBDescriptorProto_Builder*) setName:(NSString*) value;
- (PBDescriptorProto_Builder*) clearName;

- (PBAppendableArray *)field;
- (PBFieldDescriptorProto*)fieldAtIndex:(NSUInteger)index;
- (PBDescriptorProto_Builder *)addField:(PBFieldDescriptorProto*)value;
- (PBDescriptorProto_Builder *)setFieldArray:(NSArray *)array;
- (PBDescriptorProto_Builder *)setFieldValues:(const PBFieldDescriptorProto* *)values count:(NSUInteger)count;
- (PBDescriptorProto_Builder *)clearField;

- (PBAppendableArray *)extension;
- (PBFieldDescriptorProto*)extensionAtIndex:(NSUInteger)index;
- (PBDescriptorProto_Builder *)addExtension:(PBFieldDescriptorProto*)value;
- (PBDescriptorProto_Builder *)setExtensionArray:(NSArray *)array;
- (PBDescriptorProto_Builder *)setExtensionValues:(const PBFieldDescriptorProto* *)values count:(NSUInteger)count;
- (PBDescriptorProto_Builder *)clearExtension;

- (PBAppendableArray *)nestedType;
- (PBDescriptorProto*)nestedTypeAtIndex:(NSUInteger)index;
- (PBDescriptorProto_Builder *)addNestedType:(PBDescriptorProto*)value;
- (PBDescriptorProto_Builder *)setNestedTypeArray:(NSArray *)array;
- (PBDescriptorProto_Builder *)setNestedTypeValues:(const PBDescriptorProto* *)values count:(NSUInteger)count;
- (PBDescriptorProto_Builder *)clearNestedType;

- (PBAppendableArray *)enumType;
- (PBEnumDescriptorProto*)enumTypeAtIndex:(NSUInteger)index;
- (PBDescriptorProto_Builder *)addEnumType:(PBEnumDescriptorProto*)value;
- (PBDescriptorProto_Builder *)setEnumTypeArray:(NSArray *)array;
- (PBDescriptorProto_Builder *)setEnumTypeValues:(const PBEnumDescriptorProto* *)values count:(NSUInteger)count;
- (PBDescriptorProto_Builder *)clearEnumType;

- (PBAppendableArray *)extensionRange;
- (PBDescriptorProto_ExtensionRange*)extensionRangeAtIndex:(NSUInteger)index;
- (PBDescriptorProto_Builder *)addExtensionRange:(PBDescriptorProto_ExtensionRange*)value;
- (PBDescriptorProto_Builder *)setExtensionRangeArray:(NSArray *)array;
- (PBDescriptorProto_Builder *)setExtensionRangeValues:(const PBDescriptorProto_ExtensionRange* *)values count:(NSUInteger)count;
- (PBDescriptorProto_Builder *)clearExtensionRange;

- (BOOL) hasOptions;
- (PBMessageOptions*) options;
- (PBDescriptorProto_Builder*) setOptions:(PBMessageOptions*) value;
- (PBDescriptorProto_Builder*) setOptionsBuilder:(PBMessageOptions_Builder*) builderForValue;
- (PBDescriptorProto_Builder*) mergeOptions:(PBMessageOptions*) value;
- (PBDescriptorProto_Builder*) clearOptions;
@end

@interface PBFieldDescriptorProto : PBGeneratedMessage {
@private
  BOOL hasNumber_:1;
  BOOL hasName_:1;
  BOOL hasTypeName_:1;
  BOOL hasExtendee_:1;
  BOOL hasDefaultValue_:1;
  BOOL hasOptions_:1;
  BOOL hasLabel_:1;
  BOOL hasType_:1;
  int32_t number;
  NSString* name;
  NSString* typeName;
  NSString* extendee;
  NSString* defaultValue;
  PBFieldOptions* options;
  PBFieldDescriptorProto_Label label;
  PBFieldDescriptorProto_Type type;
}
- (BOOL) hasName;
- (BOOL) hasNumber;
- (BOOL) hasLabel;
- (BOOL) hasType;
- (BOOL) hasTypeName;
- (BOOL) hasExtendee;
- (BOOL) hasDefaultValue;
- (BOOL) hasOptions;
@property (readonly, retain) NSString* name;
@property (readonly) int32_t number;
@property (readonly) PBFieldDescriptorProto_Label label;
@property (readonly) PBFieldDescriptorProto_Type type;
@property (readonly, retain) NSString* typeName;
@property (readonly, retain) NSString* extendee;
@property (readonly, retain) NSString* defaultValue;
@property (readonly, retain) PBFieldOptions* options;

+ (PBFieldDescriptorProto*) defaultInstance;
- (PBFieldDescriptorProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBFieldDescriptorProto_Builder*) builder;
+ (PBFieldDescriptorProto_Builder*) builder;
+ (PBFieldDescriptorProto_Builder*) builderWithPrototype:(PBFieldDescriptorProto*) prototype;

+ (PBFieldDescriptorProto*) parseFromData:(NSData*) data;
+ (PBFieldDescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFieldDescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (PBFieldDescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFieldDescriptorProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBFieldDescriptorProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBFieldDescriptorProto_Builder : PBGeneratedMessage_Builder {
@private
  PBFieldDescriptorProto* result;
}

- (PBFieldDescriptorProto*) defaultInstance;

- (PBFieldDescriptorProto_Builder*) clear;
- (PBFieldDescriptorProto_Builder*) clone;

- (PBFieldDescriptorProto*) build;
- (PBFieldDescriptorProto*) buildPartial;

- (PBFieldDescriptorProto_Builder*) mergeFrom:(PBFieldDescriptorProto*) other;
- (PBFieldDescriptorProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBFieldDescriptorProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (PBFieldDescriptorProto_Builder*) setName:(NSString*) value;
- (PBFieldDescriptorProto_Builder*) clearName;

- (BOOL) hasNumber;
- (int32_t) number;
- (PBFieldDescriptorProto_Builder*) setNumber:(int32_t) value;
- (PBFieldDescriptorProto_Builder*) clearNumber;

- (BOOL) hasLabel;
- (PBFieldDescriptorProto_Label) label;
- (PBFieldDescriptorProto_Builder*) setLabel:(PBFieldDescriptorProto_Label) value;
- (PBFieldDescriptorProto_Builder*) clearLabel;

- (BOOL) hasType;
- (PBFieldDescriptorProto_Type) type;
- (PBFieldDescriptorProto_Builder*) setType:(PBFieldDescriptorProto_Type) value;
- (PBFieldDescriptorProto_Builder*) clearType;

- (BOOL) hasTypeName;
- (NSString*) typeName;
- (PBFieldDescriptorProto_Builder*) setTypeName:(NSString*) value;
- (PBFieldDescriptorProto_Builder*) clearTypeName;

- (BOOL) hasExtendee;
- (NSString*) extendee;
- (PBFieldDescriptorProto_Builder*) setExtendee:(NSString*) value;
- (PBFieldDescriptorProto_Builder*) clearExtendee;

- (BOOL) hasDefaultValue;
- (NSString*) defaultValue;
- (PBFieldDescriptorProto_Builder*) setDefaultValue:(NSString*) value;
- (PBFieldDescriptorProto_Builder*) clearDefaultValue;

- (BOOL) hasOptions;
- (PBFieldOptions*) options;
- (PBFieldDescriptorProto_Builder*) setOptions:(PBFieldOptions*) value;
- (PBFieldDescriptorProto_Builder*) setOptionsBuilder:(PBFieldOptions_Builder*) builderForValue;
- (PBFieldDescriptorProto_Builder*) mergeOptions:(PBFieldOptions*) value;
- (PBFieldDescriptorProto_Builder*) clearOptions;
@end

@interface PBEnumDescriptorProto : PBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasOptions_:1;
  NSString* name;
  PBEnumOptions* options;
  PBAppendableArray * valueArray;
}
- (BOOL) hasName;
- (BOOL) hasOptions;
@property (readonly, retain) NSString* name;
@property (readonly, retain) PBArray * value;
@property (readonly, retain) PBEnumOptions* options;
- (PBEnumValueDescriptorProto*)valueAtIndex:(NSUInteger)index;

+ (PBEnumDescriptorProto*) defaultInstance;
- (PBEnumDescriptorProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBEnumDescriptorProto_Builder*) builder;
+ (PBEnumDescriptorProto_Builder*) builder;
+ (PBEnumDescriptorProto_Builder*) builderWithPrototype:(PBEnumDescriptorProto*) prototype;

+ (PBEnumDescriptorProto*) parseFromData:(NSData*) data;
+ (PBEnumDescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBEnumDescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (PBEnumDescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBEnumDescriptorProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBEnumDescriptorProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBEnumDescriptorProto_Builder : PBGeneratedMessage_Builder {
@private
  PBEnumDescriptorProto* result;
}

- (PBEnumDescriptorProto*) defaultInstance;

- (PBEnumDescriptorProto_Builder*) clear;
- (PBEnumDescriptorProto_Builder*) clone;

- (PBEnumDescriptorProto*) build;
- (PBEnumDescriptorProto*) buildPartial;

- (PBEnumDescriptorProto_Builder*) mergeFrom:(PBEnumDescriptorProto*) other;
- (PBEnumDescriptorProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBEnumDescriptorProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (PBEnumDescriptorProto_Builder*) setName:(NSString*) value;
- (PBEnumDescriptorProto_Builder*) clearName;

- (PBAppendableArray *)value;
- (PBEnumValueDescriptorProto*)valueAtIndex:(NSUInteger)index;
- (PBEnumDescriptorProto_Builder *)addValue:(PBEnumValueDescriptorProto*)value;
- (PBEnumDescriptorProto_Builder *)setValueArray:(NSArray *)array;
- (PBEnumDescriptorProto_Builder *)setValueValues:(const PBEnumValueDescriptorProto* *)values count:(NSUInteger)count;
- (PBEnumDescriptorProto_Builder *)clearValue;

- (BOOL) hasOptions;
- (PBEnumOptions*) options;
- (PBEnumDescriptorProto_Builder*) setOptions:(PBEnumOptions*) value;
- (PBEnumDescriptorProto_Builder*) setOptionsBuilder:(PBEnumOptions_Builder*) builderForValue;
- (PBEnumDescriptorProto_Builder*) mergeOptions:(PBEnumOptions*) value;
- (PBEnumDescriptorProto_Builder*) clearOptions;
@end

@interface PBEnumValueDescriptorProto : PBGeneratedMessage {
@private
  BOOL hasNumber_:1;
  BOOL hasName_:1;
  BOOL hasOptions_:1;
  int32_t number;
  NSString* name;
  PBEnumValueOptions* options;
}
- (BOOL) hasName;
- (BOOL) hasNumber;
- (BOOL) hasOptions;
@property (readonly, retain) NSString* name;
@property (readonly) int32_t number;
@property (readonly, retain) PBEnumValueOptions* options;

+ (PBEnumValueDescriptorProto*) defaultInstance;
- (PBEnumValueDescriptorProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBEnumValueDescriptorProto_Builder*) builder;
+ (PBEnumValueDescriptorProto_Builder*) builder;
+ (PBEnumValueDescriptorProto_Builder*) builderWithPrototype:(PBEnumValueDescriptorProto*) prototype;

+ (PBEnumValueDescriptorProto*) parseFromData:(NSData*) data;
+ (PBEnumValueDescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBEnumValueDescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (PBEnumValueDescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBEnumValueDescriptorProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBEnumValueDescriptorProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBEnumValueDescriptorProto_Builder : PBGeneratedMessage_Builder {
@private
  PBEnumValueDescriptorProto* result;
}

- (PBEnumValueDescriptorProto*) defaultInstance;

- (PBEnumValueDescriptorProto_Builder*) clear;
- (PBEnumValueDescriptorProto_Builder*) clone;

- (PBEnumValueDescriptorProto*) build;
- (PBEnumValueDescriptorProto*) buildPartial;

- (PBEnumValueDescriptorProto_Builder*) mergeFrom:(PBEnumValueDescriptorProto*) other;
- (PBEnumValueDescriptorProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBEnumValueDescriptorProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (PBEnumValueDescriptorProto_Builder*) setName:(NSString*) value;
- (PBEnumValueDescriptorProto_Builder*) clearName;

- (BOOL) hasNumber;
- (int32_t) number;
- (PBEnumValueDescriptorProto_Builder*) setNumber:(int32_t) value;
- (PBEnumValueDescriptorProto_Builder*) clearNumber;

- (BOOL) hasOptions;
- (PBEnumValueOptions*) options;
- (PBEnumValueDescriptorProto_Builder*) setOptions:(PBEnumValueOptions*) value;
- (PBEnumValueDescriptorProto_Builder*) setOptionsBuilder:(PBEnumValueOptions_Builder*) builderForValue;
- (PBEnumValueDescriptorProto_Builder*) mergeOptions:(PBEnumValueOptions*) value;
- (PBEnumValueDescriptorProto_Builder*) clearOptions;
@end

@interface PBServiceDescriptorProto : PBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasOptions_:1;
  NSString* name;
  PBServiceOptions* options;
  PBAppendableArray * methodArray;
}
- (BOOL) hasName;
- (BOOL) hasOptions;
@property (readonly, retain) NSString* name;
@property (readonly, retain) PBArray * method;
@property (readonly, retain) PBServiceOptions* options;
- (PBMethodDescriptorProto*)methodAtIndex:(NSUInteger)index;

+ (PBServiceDescriptorProto*) defaultInstance;
- (PBServiceDescriptorProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBServiceDescriptorProto_Builder*) builder;
+ (PBServiceDescriptorProto_Builder*) builder;
+ (PBServiceDescriptorProto_Builder*) builderWithPrototype:(PBServiceDescriptorProto*) prototype;

+ (PBServiceDescriptorProto*) parseFromData:(NSData*) data;
+ (PBServiceDescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBServiceDescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (PBServiceDescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBServiceDescriptorProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBServiceDescriptorProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBServiceDescriptorProto_Builder : PBGeneratedMessage_Builder {
@private
  PBServiceDescriptorProto* result;
}

- (PBServiceDescriptorProto*) defaultInstance;

- (PBServiceDescriptorProto_Builder*) clear;
- (PBServiceDescriptorProto_Builder*) clone;

- (PBServiceDescriptorProto*) build;
- (PBServiceDescriptorProto*) buildPartial;

- (PBServiceDescriptorProto_Builder*) mergeFrom:(PBServiceDescriptorProto*) other;
- (PBServiceDescriptorProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBServiceDescriptorProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (PBServiceDescriptorProto_Builder*) setName:(NSString*) value;
- (PBServiceDescriptorProto_Builder*) clearName;

- (PBAppendableArray *)method;
- (PBMethodDescriptorProto*)methodAtIndex:(NSUInteger)index;
- (PBServiceDescriptorProto_Builder *)addMethod:(PBMethodDescriptorProto*)value;
- (PBServiceDescriptorProto_Builder *)setMethodArray:(NSArray *)array;
- (PBServiceDescriptorProto_Builder *)setMethodValues:(const PBMethodDescriptorProto* *)values count:(NSUInteger)count;
- (PBServiceDescriptorProto_Builder *)clearMethod;

- (BOOL) hasOptions;
- (PBServiceOptions*) options;
- (PBServiceDescriptorProto_Builder*) setOptions:(PBServiceOptions*) value;
- (PBServiceDescriptorProto_Builder*) setOptionsBuilder:(PBServiceOptions_Builder*) builderForValue;
- (PBServiceDescriptorProto_Builder*) mergeOptions:(PBServiceOptions*) value;
- (PBServiceDescriptorProto_Builder*) clearOptions;
@end

@interface PBMethodDescriptorProto : PBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasInputType_:1;
  BOOL hasOutputType_:1;
  BOOL hasOptions_:1;
  NSString* name;
  NSString* inputType;
  NSString* outputType;
  PBMethodOptions* options;
}
- (BOOL) hasName;
- (BOOL) hasInputType;
- (BOOL) hasOutputType;
- (BOOL) hasOptions;
@property (readonly, retain) NSString* name;
@property (readonly, retain) NSString* inputType;
@property (readonly, retain) NSString* outputType;
@property (readonly, retain) PBMethodOptions* options;

+ (PBMethodDescriptorProto*) defaultInstance;
- (PBMethodDescriptorProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBMethodDescriptorProto_Builder*) builder;
+ (PBMethodDescriptorProto_Builder*) builder;
+ (PBMethodDescriptorProto_Builder*) builderWithPrototype:(PBMethodDescriptorProto*) prototype;

+ (PBMethodDescriptorProto*) parseFromData:(NSData*) data;
+ (PBMethodDescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBMethodDescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (PBMethodDescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBMethodDescriptorProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBMethodDescriptorProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBMethodDescriptorProto_Builder : PBGeneratedMessage_Builder {
@private
  PBMethodDescriptorProto* result;
}

- (PBMethodDescriptorProto*) defaultInstance;

- (PBMethodDescriptorProto_Builder*) clear;
- (PBMethodDescriptorProto_Builder*) clone;

- (PBMethodDescriptorProto*) build;
- (PBMethodDescriptorProto*) buildPartial;

- (PBMethodDescriptorProto_Builder*) mergeFrom:(PBMethodDescriptorProto*) other;
- (PBMethodDescriptorProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBMethodDescriptorProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (PBMethodDescriptorProto_Builder*) setName:(NSString*) value;
- (PBMethodDescriptorProto_Builder*) clearName;

- (BOOL) hasInputType;
- (NSString*) inputType;
- (PBMethodDescriptorProto_Builder*) setInputType:(NSString*) value;
- (PBMethodDescriptorProto_Builder*) clearInputType;

- (BOOL) hasOutputType;
- (NSString*) outputType;
- (PBMethodDescriptorProto_Builder*) setOutputType:(NSString*) value;
- (PBMethodDescriptorProto_Builder*) clearOutputType;

- (BOOL) hasOptions;
- (PBMethodOptions*) options;
- (PBMethodDescriptorProto_Builder*) setOptions:(PBMethodOptions*) value;
- (PBMethodDescriptorProto_Builder*) setOptionsBuilder:(PBMethodOptions_Builder*) builderForValue;
- (PBMethodDescriptorProto_Builder*) mergeOptions:(PBMethodOptions*) value;
- (PBMethodDescriptorProto_Builder*) clearOptions;
@end

@interface PBFileOptions : PBExtendableMessage {
@private
  BOOL hasJavaMultipleFiles_:1;
  BOOL hasCcGenericServices_:1;
  BOOL hasJavaGenericServices_:1;
  BOOL hasPyGenericServices_:1;
  BOOL hasJavaPackage_:1;
  BOOL hasJavaOuterClassname_:1;
  BOOL hasOptimizeFor_:1;
  BOOL javaMultipleFiles_:1;
  BOOL ccGenericServices_:1;
  BOOL javaGenericServices_:1;
  BOOL pyGenericServices_:1;
  NSString* javaPackage;
  NSString* javaOuterClassname;
  PBFileOptions_OptimizeMode optimizeFor;
  PBAppendableArray * uninterpretedOptionArray;
}
- (BOOL) hasJavaPackage;
- (BOOL) hasJavaOuterClassname;
- (BOOL) hasJavaMultipleFiles;
- (BOOL) hasOptimizeFor;
- (BOOL) hasCcGenericServices;
- (BOOL) hasJavaGenericServices;
- (BOOL) hasPyGenericServices;
@property (readonly, retain) NSString* javaPackage;
@property (readonly, retain) NSString* javaOuterClassname;
- (BOOL) javaMultipleFiles;
@property (readonly) PBFileOptions_OptimizeMode optimizeFor;
- (BOOL) ccGenericServices;
- (BOOL) javaGenericServices;
- (BOOL) pyGenericServices;
@property (readonly, retain) PBArray * uninterpretedOption;
- (PBUninterpretedOption*)uninterpretedOptionAtIndex:(NSUInteger)index;

+ (PBFileOptions*) defaultInstance;
- (PBFileOptions*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBFileOptions_Builder*) builder;
+ (PBFileOptions_Builder*) builder;
+ (PBFileOptions_Builder*) builderWithPrototype:(PBFileOptions*) prototype;

+ (PBFileOptions*) parseFromData:(NSData*) data;
+ (PBFileOptions*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFileOptions*) parseFromInputStream:(NSInputStream*) input;
+ (PBFileOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFileOptions*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBFileOptions*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBFileOptions_Builder : PBExtendableMessage_Builder {
@private
  PBFileOptions* result;
}

- (PBFileOptions*) defaultInstance;

- (PBFileOptions_Builder*) clear;
- (PBFileOptions_Builder*) clone;

- (PBFileOptions*) build;
- (PBFileOptions*) buildPartial;

- (PBFileOptions_Builder*) mergeFrom:(PBFileOptions*) other;
- (PBFileOptions_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBFileOptions_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasJavaPackage;
- (NSString*) javaPackage;
- (PBFileOptions_Builder*) setJavaPackage:(NSString*) value;
- (PBFileOptions_Builder*) clearJavaPackage;

- (BOOL) hasJavaOuterClassname;
- (NSString*) javaOuterClassname;
- (PBFileOptions_Builder*) setJavaOuterClassname:(NSString*) value;
- (PBFileOptions_Builder*) clearJavaOuterClassname;

- (BOOL) hasJavaMultipleFiles;
- (BOOL) javaMultipleFiles;
- (PBFileOptions_Builder*) setJavaMultipleFiles:(BOOL) value;
- (PBFileOptions_Builder*) clearJavaMultipleFiles;

- (BOOL) hasOptimizeFor;
- (PBFileOptions_OptimizeMode) optimizeFor;
- (PBFileOptions_Builder*) setOptimizeFor:(PBFileOptions_OptimizeMode) value;
- (PBFileOptions_Builder*) clearOptimizeFor;

- (BOOL) hasCcGenericServices;
- (BOOL) ccGenericServices;
- (PBFileOptions_Builder*) setCcGenericServices:(BOOL) value;
- (PBFileOptions_Builder*) clearCcGenericServices;

- (BOOL) hasJavaGenericServices;
- (BOOL) javaGenericServices;
- (PBFileOptions_Builder*) setJavaGenericServices:(BOOL) value;
- (PBFileOptions_Builder*) clearJavaGenericServices;

- (BOOL) hasPyGenericServices;
- (BOOL) pyGenericServices;
- (PBFileOptions_Builder*) setPyGenericServices:(BOOL) value;
- (PBFileOptions_Builder*) clearPyGenericServices;

- (PBAppendableArray *)uninterpretedOption;
- (PBUninterpretedOption*)uninterpretedOptionAtIndex:(NSUInteger)index;
- (PBFileOptions_Builder *)addUninterpretedOption:(PBUninterpretedOption*)value;
- (PBFileOptions_Builder *)setUninterpretedOptionArray:(NSArray *)array;
- (PBFileOptions_Builder *)setUninterpretedOptionValues:(const PBUninterpretedOption* *)values count:(NSUInteger)count;
- (PBFileOptions_Builder *)clearUninterpretedOption;
@end

@interface PBMessageOptions : PBExtendableMessage {
@private
  BOOL hasMessageSetWireFormat_:1;
  BOOL hasNoStandardDescriptorAccessor_:1;
  BOOL messageSetWireFormat_:1;
  BOOL noStandardDescriptorAccessor_:1;
  PBAppendableArray * uninterpretedOptionArray;
}
- (BOOL) hasMessageSetWireFormat;
- (BOOL) hasNoStandardDescriptorAccessor;
- (BOOL) messageSetWireFormat;
- (BOOL) noStandardDescriptorAccessor;
@property (readonly, retain) PBArray * uninterpretedOption;
- (PBUninterpretedOption*)uninterpretedOptionAtIndex:(NSUInteger)index;

+ (PBMessageOptions*) defaultInstance;
- (PBMessageOptions*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBMessageOptions_Builder*) builder;
+ (PBMessageOptions_Builder*) builder;
+ (PBMessageOptions_Builder*) builderWithPrototype:(PBMessageOptions*) prototype;

+ (PBMessageOptions*) parseFromData:(NSData*) data;
+ (PBMessageOptions*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBMessageOptions*) parseFromInputStream:(NSInputStream*) input;
+ (PBMessageOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBMessageOptions*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBMessageOptions*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBMessageOptions_Builder : PBExtendableMessage_Builder {
@private
  PBMessageOptions* result;
}

- (PBMessageOptions*) defaultInstance;

- (PBMessageOptions_Builder*) clear;
- (PBMessageOptions_Builder*) clone;

- (PBMessageOptions*) build;
- (PBMessageOptions*) buildPartial;

- (PBMessageOptions_Builder*) mergeFrom:(PBMessageOptions*) other;
- (PBMessageOptions_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBMessageOptions_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMessageSetWireFormat;
- (BOOL) messageSetWireFormat;
- (PBMessageOptions_Builder*) setMessageSetWireFormat:(BOOL) value;
- (PBMessageOptions_Builder*) clearMessageSetWireFormat;

- (BOOL) hasNoStandardDescriptorAccessor;
- (BOOL) noStandardDescriptorAccessor;
- (PBMessageOptions_Builder*) setNoStandardDescriptorAccessor:(BOOL) value;
- (PBMessageOptions_Builder*) clearNoStandardDescriptorAccessor;

- (PBAppendableArray *)uninterpretedOption;
- (PBUninterpretedOption*)uninterpretedOptionAtIndex:(NSUInteger)index;
- (PBMessageOptions_Builder *)addUninterpretedOption:(PBUninterpretedOption*)value;
- (PBMessageOptions_Builder *)setUninterpretedOptionArray:(NSArray *)array;
- (PBMessageOptions_Builder *)setUninterpretedOptionValues:(const PBUninterpretedOption* *)values count:(NSUInteger)count;
- (PBMessageOptions_Builder *)clearUninterpretedOption;
@end

@interface PBFieldOptions : PBExtendableMessage {
@private
  BOOL hasPacked_:1;
  BOOL hasDeprecated_:1;
  BOOL hasExperimentalMapKey_:1;
  BOOL hasCtype_:1;
  BOOL packed_:1;
  BOOL deprecated_:1;
  NSString* experimentalMapKey;
  PBFieldOptions_CType ctype;
  PBAppendableArray * uninterpretedOptionArray;
}
- (BOOL) hasCtype;
- (BOOL) hasPacked;
- (BOOL) hasDeprecated;
- (BOOL) hasExperimentalMapKey;
@property (readonly) PBFieldOptions_CType ctype;
- (BOOL) packed;
- (BOOL) deprecated;
@property (readonly, retain) NSString* experimentalMapKey;
@property (readonly, retain) PBArray * uninterpretedOption;
- (PBUninterpretedOption*)uninterpretedOptionAtIndex:(NSUInteger)index;

+ (PBFieldOptions*) defaultInstance;
- (PBFieldOptions*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBFieldOptions_Builder*) builder;
+ (PBFieldOptions_Builder*) builder;
+ (PBFieldOptions_Builder*) builderWithPrototype:(PBFieldOptions*) prototype;

+ (PBFieldOptions*) parseFromData:(NSData*) data;
+ (PBFieldOptions*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFieldOptions*) parseFromInputStream:(NSInputStream*) input;
+ (PBFieldOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBFieldOptions*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBFieldOptions*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBFieldOptions_Builder : PBExtendableMessage_Builder {
@private
  PBFieldOptions* result;
}

- (PBFieldOptions*) defaultInstance;

- (PBFieldOptions_Builder*) clear;
- (PBFieldOptions_Builder*) clone;

- (PBFieldOptions*) build;
- (PBFieldOptions*) buildPartial;

- (PBFieldOptions_Builder*) mergeFrom:(PBFieldOptions*) other;
- (PBFieldOptions_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBFieldOptions_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCtype;
- (PBFieldOptions_CType) ctype;
- (PBFieldOptions_Builder*) setCtype:(PBFieldOptions_CType) value;
- (PBFieldOptions_Builder*) clearCtype;

- (BOOL) hasPacked;
- (BOOL) packed;
- (PBFieldOptions_Builder*) setPacked:(BOOL) value;
- (PBFieldOptions_Builder*) clearPacked;

- (BOOL) hasDeprecated;
- (BOOL) deprecated;
- (PBFieldOptions_Builder*) setDeprecated:(BOOL) value;
- (PBFieldOptions_Builder*) clearDeprecated;

- (BOOL) hasExperimentalMapKey;
- (NSString*) experimentalMapKey;
- (PBFieldOptions_Builder*) setExperimentalMapKey:(NSString*) value;
- (PBFieldOptions_Builder*) clearExperimentalMapKey;

- (PBAppendableArray *)uninterpretedOption;
- (PBUninterpretedOption*)uninterpretedOptionAtIndex:(NSUInteger)index;
- (PBFieldOptions_Builder *)addUninterpretedOption:(PBUninterpretedOption*)value;
- (PBFieldOptions_Builder *)setUninterpretedOptionArray:(NSArray *)array;
- (PBFieldOptions_Builder *)setUninterpretedOptionValues:(const PBUninterpretedOption* *)values count:(NSUInteger)count;
- (PBFieldOptions_Builder *)clearUninterpretedOption;
@end

@interface PBEnumOptions : PBExtendableMessage {
@private
  PBAppendableArray * uninterpretedOptionArray;
}
@property (readonly, retain) PBArray * uninterpretedOption;
- (PBUninterpretedOption*)uninterpretedOptionAtIndex:(NSUInteger)index;

+ (PBEnumOptions*) defaultInstance;
- (PBEnumOptions*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBEnumOptions_Builder*) builder;
+ (PBEnumOptions_Builder*) builder;
+ (PBEnumOptions_Builder*) builderWithPrototype:(PBEnumOptions*) prototype;

+ (PBEnumOptions*) parseFromData:(NSData*) data;
+ (PBEnumOptions*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBEnumOptions*) parseFromInputStream:(NSInputStream*) input;
+ (PBEnumOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBEnumOptions*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBEnumOptions*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBEnumOptions_Builder : PBExtendableMessage_Builder {
@private
  PBEnumOptions* result;
}

- (PBEnumOptions*) defaultInstance;

- (PBEnumOptions_Builder*) clear;
- (PBEnumOptions_Builder*) clone;

- (PBEnumOptions*) build;
- (PBEnumOptions*) buildPartial;

- (PBEnumOptions_Builder*) mergeFrom:(PBEnumOptions*) other;
- (PBEnumOptions_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBEnumOptions_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (PBAppendableArray *)uninterpretedOption;
- (PBUninterpretedOption*)uninterpretedOptionAtIndex:(NSUInteger)index;
- (PBEnumOptions_Builder *)addUninterpretedOption:(PBUninterpretedOption*)value;
- (PBEnumOptions_Builder *)setUninterpretedOptionArray:(NSArray *)array;
- (PBEnumOptions_Builder *)setUninterpretedOptionValues:(const PBUninterpretedOption* *)values count:(NSUInteger)count;
- (PBEnumOptions_Builder *)clearUninterpretedOption;
@end

@interface PBEnumValueOptions : PBExtendableMessage {
@private
  PBAppendableArray * uninterpretedOptionArray;
}
@property (readonly, retain) PBArray * uninterpretedOption;
- (PBUninterpretedOption*)uninterpretedOptionAtIndex:(NSUInteger)index;

+ (PBEnumValueOptions*) defaultInstance;
- (PBEnumValueOptions*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBEnumValueOptions_Builder*) builder;
+ (PBEnumValueOptions_Builder*) builder;
+ (PBEnumValueOptions_Builder*) builderWithPrototype:(PBEnumValueOptions*) prototype;

+ (PBEnumValueOptions*) parseFromData:(NSData*) data;
+ (PBEnumValueOptions*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBEnumValueOptions*) parseFromInputStream:(NSInputStream*) input;
+ (PBEnumValueOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBEnumValueOptions*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBEnumValueOptions*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBEnumValueOptions_Builder : PBExtendableMessage_Builder {
@private
  PBEnumValueOptions* result;
}

- (PBEnumValueOptions*) defaultInstance;

- (PBEnumValueOptions_Builder*) clear;
- (PBEnumValueOptions_Builder*) clone;

- (PBEnumValueOptions*) build;
- (PBEnumValueOptions*) buildPartial;

- (PBEnumValueOptions_Builder*) mergeFrom:(PBEnumValueOptions*) other;
- (PBEnumValueOptions_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBEnumValueOptions_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (PBAppendableArray *)uninterpretedOption;
- (PBUninterpretedOption*)uninterpretedOptionAtIndex:(NSUInteger)index;
- (PBEnumValueOptions_Builder *)addUninterpretedOption:(PBUninterpretedOption*)value;
- (PBEnumValueOptions_Builder *)setUninterpretedOptionArray:(NSArray *)array;
- (PBEnumValueOptions_Builder *)setUninterpretedOptionValues:(const PBUninterpretedOption* *)values count:(NSUInteger)count;
- (PBEnumValueOptions_Builder *)clearUninterpretedOption;
@end

@interface PBServiceOptions : PBExtendableMessage {
@private
  PBAppendableArray * uninterpretedOptionArray;
}
@property (readonly, retain) PBArray * uninterpretedOption;
- (PBUninterpretedOption*)uninterpretedOptionAtIndex:(NSUInteger)index;

+ (PBServiceOptions*) defaultInstance;
- (PBServiceOptions*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBServiceOptions_Builder*) builder;
+ (PBServiceOptions_Builder*) builder;
+ (PBServiceOptions_Builder*) builderWithPrototype:(PBServiceOptions*) prototype;

+ (PBServiceOptions*) parseFromData:(NSData*) data;
+ (PBServiceOptions*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBServiceOptions*) parseFromInputStream:(NSInputStream*) input;
+ (PBServiceOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBServiceOptions*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBServiceOptions*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBServiceOptions_Builder : PBExtendableMessage_Builder {
@private
  PBServiceOptions* result;
}

- (PBServiceOptions*) defaultInstance;

- (PBServiceOptions_Builder*) clear;
- (PBServiceOptions_Builder*) clone;

- (PBServiceOptions*) build;
- (PBServiceOptions*) buildPartial;

- (PBServiceOptions_Builder*) mergeFrom:(PBServiceOptions*) other;
- (PBServiceOptions_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBServiceOptions_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (PBAppendableArray *)uninterpretedOption;
- (PBUninterpretedOption*)uninterpretedOptionAtIndex:(NSUInteger)index;
- (PBServiceOptions_Builder *)addUninterpretedOption:(PBUninterpretedOption*)value;
- (PBServiceOptions_Builder *)setUninterpretedOptionArray:(NSArray *)array;
- (PBServiceOptions_Builder *)setUninterpretedOptionValues:(const PBUninterpretedOption* *)values count:(NSUInteger)count;
- (PBServiceOptions_Builder *)clearUninterpretedOption;
@end

@interface PBMethodOptions : PBExtendableMessage {
@private
  PBAppendableArray * uninterpretedOptionArray;
}
@property (readonly, retain) PBArray * uninterpretedOption;
- (PBUninterpretedOption*)uninterpretedOptionAtIndex:(NSUInteger)index;

+ (PBMethodOptions*) defaultInstance;
- (PBMethodOptions*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBMethodOptions_Builder*) builder;
+ (PBMethodOptions_Builder*) builder;
+ (PBMethodOptions_Builder*) builderWithPrototype:(PBMethodOptions*) prototype;

+ (PBMethodOptions*) parseFromData:(NSData*) data;
+ (PBMethodOptions*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBMethodOptions*) parseFromInputStream:(NSInputStream*) input;
+ (PBMethodOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBMethodOptions*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBMethodOptions*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBMethodOptions_Builder : PBExtendableMessage_Builder {
@private
  PBMethodOptions* result;
}

- (PBMethodOptions*) defaultInstance;

- (PBMethodOptions_Builder*) clear;
- (PBMethodOptions_Builder*) clone;

- (PBMethodOptions*) build;
- (PBMethodOptions*) buildPartial;

- (PBMethodOptions_Builder*) mergeFrom:(PBMethodOptions*) other;
- (PBMethodOptions_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBMethodOptions_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (PBAppendableArray *)uninterpretedOption;
- (PBUninterpretedOption*)uninterpretedOptionAtIndex:(NSUInteger)index;
- (PBMethodOptions_Builder *)addUninterpretedOption:(PBUninterpretedOption*)value;
- (PBMethodOptions_Builder *)setUninterpretedOptionArray:(NSArray *)array;
- (PBMethodOptions_Builder *)setUninterpretedOptionValues:(const PBUninterpretedOption* *)values count:(NSUInteger)count;
- (PBMethodOptions_Builder *)clearUninterpretedOption;
@end

@interface PBUninterpretedOption : PBGeneratedMessage {
@private
  BOOL hasDoubleValue_:1;
  BOOL hasNegativeIntValue_:1;
  BOOL hasPositiveIntValue_:1;
  BOOL hasIdentifierValue_:1;
  BOOL hasStringValue_:1;
  Float64 doubleValue;
  int64_t negativeIntValue;
  int64_t positiveIntValue;
  NSString* identifierValue;
  NSData* stringValue;
  PBAppendableArray * nameArray;
}
- (BOOL) hasIdentifierValue;
- (BOOL) hasPositiveIntValue;
- (BOOL) hasNegativeIntValue;
- (BOOL) hasDoubleValue;
- (BOOL) hasStringValue;
@property (readonly, retain) PBArray * name;
@property (readonly, retain) NSString* identifierValue;
@property (readonly) int64_t positiveIntValue;
@property (readonly) int64_t negativeIntValue;
@property (readonly) Float64 doubleValue;
@property (readonly, retain) NSData* stringValue;
- (PBUninterpretedOption_NamePart*)nameAtIndex:(NSUInteger)index;

+ (PBUninterpretedOption*) defaultInstance;
- (PBUninterpretedOption*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBUninterpretedOption_Builder*) builder;
+ (PBUninterpretedOption_Builder*) builder;
+ (PBUninterpretedOption_Builder*) builderWithPrototype:(PBUninterpretedOption*) prototype;

+ (PBUninterpretedOption*) parseFromData:(NSData*) data;
+ (PBUninterpretedOption*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBUninterpretedOption*) parseFromInputStream:(NSInputStream*) input;
+ (PBUninterpretedOption*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBUninterpretedOption*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBUninterpretedOption*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBUninterpretedOption_NamePart : PBGeneratedMessage {
@private
  BOOL hasIsExtension_:1;
  BOOL hasNamePart_:1;
  BOOL isExtension_:1;
  NSString* namePart;
}
- (BOOL) hasNamePart;
- (BOOL) hasIsExtension;
@property (readonly, retain) NSString* namePart;
- (BOOL) isExtension;

+ (PBUninterpretedOption_NamePart*) defaultInstance;
- (PBUninterpretedOption_NamePart*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBUninterpretedOption_NamePart_Builder*) builder;
+ (PBUninterpretedOption_NamePart_Builder*) builder;
+ (PBUninterpretedOption_NamePart_Builder*) builderWithPrototype:(PBUninterpretedOption_NamePart*) prototype;

+ (PBUninterpretedOption_NamePart*) parseFromData:(NSData*) data;
+ (PBUninterpretedOption_NamePart*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBUninterpretedOption_NamePart*) parseFromInputStream:(NSInputStream*) input;
+ (PBUninterpretedOption_NamePart*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBUninterpretedOption_NamePart*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBUninterpretedOption_NamePart*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBUninterpretedOption_NamePart_Builder : PBGeneratedMessage_Builder {
@private
  PBUninterpretedOption_NamePart* result;
}

- (PBUninterpretedOption_NamePart*) defaultInstance;

- (PBUninterpretedOption_NamePart_Builder*) clear;
- (PBUninterpretedOption_NamePart_Builder*) clone;

- (PBUninterpretedOption_NamePart*) build;
- (PBUninterpretedOption_NamePart*) buildPartial;

- (PBUninterpretedOption_NamePart_Builder*) mergeFrom:(PBUninterpretedOption_NamePart*) other;
- (PBUninterpretedOption_NamePart_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBUninterpretedOption_NamePart_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasNamePart;
- (NSString*) namePart;
- (PBUninterpretedOption_NamePart_Builder*) setNamePart:(NSString*) value;
- (PBUninterpretedOption_NamePart_Builder*) clearNamePart;

- (BOOL) hasIsExtension;
- (BOOL) isExtension;
- (PBUninterpretedOption_NamePart_Builder*) setIsExtension:(BOOL) value;
- (PBUninterpretedOption_NamePart_Builder*) clearIsExtension;
@end

@interface PBUninterpretedOption_Builder : PBGeneratedMessage_Builder {
@private
  PBUninterpretedOption* result;
}

- (PBUninterpretedOption*) defaultInstance;

- (PBUninterpretedOption_Builder*) clear;
- (PBUninterpretedOption_Builder*) clone;

- (PBUninterpretedOption*) build;
- (PBUninterpretedOption*) buildPartial;

- (PBUninterpretedOption_Builder*) mergeFrom:(PBUninterpretedOption*) other;
- (PBUninterpretedOption_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBUninterpretedOption_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (PBAppendableArray *)name;
- (PBUninterpretedOption_NamePart*)nameAtIndex:(NSUInteger)index;
- (PBUninterpretedOption_Builder *)addName:(PBUninterpretedOption_NamePart*)value;
- (PBUninterpretedOption_Builder *)setNameArray:(NSArray *)array;
- (PBUninterpretedOption_Builder *)setNameValues:(const PBUninterpretedOption_NamePart* *)values count:(NSUInteger)count;
- (PBUninterpretedOption_Builder *)clearName;

- (BOOL) hasIdentifierValue;
- (NSString*) identifierValue;
- (PBUninterpretedOption_Builder*) setIdentifierValue:(NSString*) value;
- (PBUninterpretedOption_Builder*) clearIdentifierValue;

- (BOOL) hasPositiveIntValue;
- (int64_t) positiveIntValue;
- (PBUninterpretedOption_Builder*) setPositiveIntValue:(int64_t) value;
- (PBUninterpretedOption_Builder*) clearPositiveIntValue;

- (BOOL) hasNegativeIntValue;
- (int64_t) negativeIntValue;
- (PBUninterpretedOption_Builder*) setNegativeIntValue:(int64_t) value;
- (PBUninterpretedOption_Builder*) clearNegativeIntValue;

- (BOOL) hasDoubleValue;
- (Float64) doubleValue;
- (PBUninterpretedOption_Builder*) setDoubleValue:(Float64) value;
- (PBUninterpretedOption_Builder*) clearDoubleValue;

- (BOOL) hasStringValue;
- (NSData*) stringValue;
- (PBUninterpretedOption_Builder*) setStringValue:(NSData*) value;
- (PBUninterpretedOption_Builder*) clearStringValue;
@end

