/* Copyright (C) 2009-2010 Mikkel Krautz <mikkel@krautz.dk>
   Copyright (c) 2005-2010 Thorvald Natvig, <thorvald@natvig.com>

   All rights reserved.

   Redistribution and use in source and binary forms, with or without
   modification, are permitted provided that the following conditions
   are met:

   - Redistributions of source code must retain the above copyright notice,
     this list of conditions and the following disclaimer.
   - Redistributions in binary form must reproduce the above copyright notice,
     this list of conditions and the following disclaimer in the documentation
     and/or other materials provided with the distribution.
   - Neither the name of the Mumble Developers nor the names of its
     contributors may be used to endorse or promote products derived from this
     software without specific prior written permission.

   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
   ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
   LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
   A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR
   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
   EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
   PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
   PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
   LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
   NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#include <openssl/evp.h>
#include <openssl/err.h>
#include <openssl/bio.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include <openssl/pkcs12.h>

#import <MumbleKit/MKCertificate.h>

static int add_ext(X509 * crt, int nid, char *value) {
	X509_EXTENSION *ex;
	X509V3_CTX ctx;
	X509V3_set_ctx_nodb(&ctx);
	X509V3_set_ctx(&ctx, crt, crt, NULL, NULL, 0);
	ex = X509V3_EXT_conf_nid(NULL, &ctx, nid, value);
	if (!ex)
		return 0;
	
	X509_add_ext(crt, ex, -1);
	X509_EXTENSION_free(ex);
	return 1;
}

@interface MKCertificate (Private)
- (void) setCertificate:(NSData *)cert;
- (NSData *) certificate;
- (void) setPrivateKey:(NSData *)pkey;
- (NSData *) privateKey;
@end

@implementation MKCertificate

// fixme(mkrautz): Move this function somewhere else if other pieces of the library
//                 needs OpenSSL.
+ (void) initialize {
	// Make sure OpenSSL is initialized...
	OpenSSL_add_all_algorithms();

	// On Unix systems OpenSSL makes sure its PRNG is seeded with
	// random data from /dev/random or /dev/urandom. It would probably
	// be a good idea to seed it more than this. Fixme?
}

- (void) dealloc {
	[_derCert release];
	[_derPrivKey release];
	[super dealloc];
}

- (void) setCertificate:(NSData *)cert {
	_derCert = [cert retain];
}

- (NSData *) certificate {
	return _derCert;
}

- (void) setPrivateKey:(NSData *)pkey {
	_derPrivKey = [pkey retain];
}

- (NSData *) privateKey {
	return _derPrivKey;
}

+ (MKCertificate *) selfSignedCertificateWithName:(NSString *)aName email:(NSString *)anEmail {
	CRYPTO_mem_ctrl(CRYPTO_MEM_CHECK_ON);

	X509 *x509 = X509_new();
	EVP_PKEY *pkey = EVP_PKEY_new();
	RSA *rsa = RSA_generate_key(2048, RSA_F4, NULL, NULL);
	EVP_PKEY_assign_RSA(pkey, rsa);

	X509_set_version(x509, 2);
	ASN1_INTEGER_set(X509_get_serialNumber(x509),1);
	X509_gmtime_adj(X509_get_notBefore(x509),0);
	X509_gmtime_adj(X509_get_notAfter(x509),60*60*24*365*20);
	X509_set_pubkey(x509, pkey);

	X509_NAME *name = X509_get_subject_name(x509);

	NSString *certName = aName;
	if (certName == nil) {
		certName = @"Mumble User";
	}

	NSString *certEmail = nil;
	if (anEmail == nil)
		anEmail = @"";
	certEmail = [NSString stringWithFormat:@"email:%@", anEmail];

	X509_NAME_add_entry_by_txt(name, "CN", MBSTRING_ASC, (unsigned char *)[certName UTF8String], -1, -1, 0);
	X509_set_issuer_name(x509, name);
	add_ext(x509, NID_basic_constraints, "critical,CA:FALSE");
	add_ext(x509, NID_ext_key_usage, "clientAuth");
	add_ext(x509, NID_subject_key_identifier, "hash");
	add_ext(x509, NID_netscape_comment, "Generated by Mumble");
	add_ext(x509, NID_subject_alt_name, (char *)[certEmail UTF8String]);

	X509_sign(x509, pkey, EVP_sha1());

	MKCertificate *cert = [[MKCertificate alloc] init];
	{
		NSMutableData *data = [[NSMutableData alloc] initWithLength:i2d_X509(x509, NULL)];
		unsigned char *ptr = [data mutableBytes];
		i2d_X509(x509, &ptr);
		[cert setCertificate:data];
		[data release];
	}
	{
		NSMutableData *data = [[NSMutableData alloc] initWithLength:i2d_PrivateKey(pkey, NULL)];
		unsigned char *ptr = [data mutableBytes];
		i2d_PrivateKey(pkey, &ptr);
		[cert setPrivateKey:data];
		[data release];
	}
	
	X509_free(x509);

	return [cert autorelease];
}

- (NSData *) exportPKCS12WithPassword:(NSString *)password {
	X509 *x509 = NULL;
	EVP_PKEY *pkey = NULL;
	PKCS12 *pkcs = NULL;
	BIO *mem = NULL;
	STACK_OF(X509) *certs = sk_X509_new_null();
	const unsigned char *p;
	long size;
	char *data = NULL;
	NSData *retData = nil;

	if (!_derCert || !_derPrivKey) {
		return nil;
	}

	p = [_derPrivKey bytes];
	pkey = d2i_AutoPrivateKey(NULL, &p, [_derPrivKey length]);

	if (pkey) {
		p = [_derCert bytes];
		x509 = d2i_X509(NULL, &p, [_derCert length]);

		if (x509 && X509_check_private_key(x509, pkey)) {
			X509_keyid_set1(x509, NULL, 0);
			X509_alias_set1(x509, NULL, 0);

			/* fixme(mkrautz): Currently we only support exporting our own self-signed certs,
			   which obviously do not have any intermediate certifictes. If we need to add
			   this in the future, do this: */
#if 0
			for (/* each certificate*/) {
				unsigned char *p = [data bytes];
				X509 *c = d2i_X509(NULL, &p, [data len])
				if (c)
					sk_X509_push(certs, c);
			}
#endif

			pkcs = PKCS12_create(password ? [password UTF8String] : NULL, "Mumble Identity", pkey, x509, certs, 0, 0, 0, 0, 0);
			if (pkcs) {
				mem = BIO_new(BIO_s_mem());
				i2d_PKCS12_bio(mem, pkcs);
				BIO_flush(mem);
				size = BIO_get_mem_data(mem, &data);
				retData = [[NSData alloc] initWithBytes:data length:size];
			}
		}
	}

	if (pkey)
		EVP_PKEY_free(pkey);
	if (x509)
		X509_free(x509);
	if (pkcs)
		PKCS12_free(pkcs);
	if (mem)
		BIO_free(mem);
	if (certs)
		sk_X509_free(certs);

	return [retData autorelease];
}

@end
